name: Build sheet music with LilyPond
on: [push]
jobs:
  build-sheet-music:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Generate PDF music sheets
      uses: alexandre-touret/lilypond-github-action@master
      with:
        args: -V --include=/github/workspace --pdf silent-night.ly